rootProject.name = "spring-boot"

include("web-core")
include("gateway")

include("common")
include("message")
include("validation")
include("items-login-application")
include("exception")
include("type-converter")
include("file-storage")
include("jdbc")

include(":domain:members")
include(":domain:items")
include(":web:session")

include(":basic:http")
include(":basic:thymeleaf")
include(":basic:items")
include(":basic:members")

include(":web:1-servlet")
include(":web:2-jsp")
include(":web:3-servlet-mvc")
include(":web:4-front-controller")
include(":web:5-spring-mvc")
