rootProject.name = "spring-boot"

include("gateway")
include(":web:core")

include(":domain:member")
include(":domain:product")
include(":domain:board")

include(":example:basic:http")
include(":example:basic:thymeleaf")
include(":example:basic:product")
include(":example:basic:members")

include(":example:web:1-servlet")
include(":example:web:2-jsp")
include(":example:web:3-servlet-mvc")
include(":example:web:4-front-controller")
include(":example:web:5-spring-mvc")

include(":example:advanced:message")
include(":example:advanced:exception")
include(":example:advanced:file-storage")
include(":example:advanced:validation")
include(":example:advanced:type-converter")
include(":example:advanced:log-tracer")
include(":example:advanced:web-server-config")
include(":example:advanced:embed-tomcat")
include(":example:advanced:auto-config")

include(":example:data:jdbc")
include(":example:data:item")
