rootProject.name = "spring-boot"

include("gateway")

include(":domain:member")
include(":domain:items")
include(":domain:files")
include(":domain:file-item")
include(":web:core")

include(":example:basic:http")
include(":example:basic:thymeleaf")
include(":example:basic:items")
include(":example:basic:members")

include(":example:web:1-servlet")
include(":example:web:2-jsp")
include(":example:web:3-servlet-mvc")
include(":example:web:4-front-controller")
include(":example:web:5-spring-mvc")

include(":example:advanced:message")
include(":example:advanced:exception")
include(":example:advanced:file-storage")
include(":example:advanced:validation")
include(":example:advanced:type-converter")

include(":example:data:jdbc")
