spring:
  main:
    allow-bean-definition-overriding: true

gateway:
  service: >
    dev.jihogrammer.items,
    dev.jihogrammer.members

logging:
  level:
#    org.apache.coyote.http11: TRACE
    dev.jihogrammer: TRACE
  pattern:
    console: "%magenta([%d{HH:MM:ss}]) %highlight([%5.5level]) [%t] %green([%25.25logger{25}]) [%X{transaction.id}] - %msg%n"
