service:
  members:
    home:
      enabled: true
    admin:
      enabled: true
  core:
    memory:
      enabled: true

logging:
  level:
    dev.jihogrammer.members: TRACE
    dev.jihogrammer.web.core: TRACE
    org.apache.coyote.http11: TRACE
  pattern:
    console:
      # %d{yyyy:mm:dd'T'HH:MM:ss.SSSZ}
      "%magenta([%d{HH:MM:ss}])
      %highlight([%5.5level])
      %green([%25.25logger{25}])
      %cyan([%X{transaction.id}]) - %msg%n"
