app.username=local_username
app.password=local_password
app.common.user=jihogrammer
app.common.hello=절대 읽히지 않는 설정

app.datasource.url=local.database.com
app.datasource.username=jihogrammer
app.datasource.password=password
app.datasource.config.max-connection=1
app.datasource.config.timeout=3500ms
app.datasource.config.options=CACHE,ADMIN

#---

spring.config.activate.on-profile=dev
app.username=dev_username
app.password=dev_password
app.common.hello=에베베 에베베

#---

spring.config.activate.on-profile=prd
app.username=prd_username
app.password=prd_password
app.common.hello=로또 당첨되면 좋겠다.

#---

spring.config.activate.on-profile=test

#---

app.common.hello=world
