plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'com.gorylenko.gradle-git-properties' version '2.4.1'
}

group = 'dev.jihogrammer.spring.boot'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

// /actuator/info API 목록에 빌드 정보 추가
// gradle bootRun 명령어로 수행할 때 동작한다. IntelliJ 자체적으로 하는 방법이 있을 것 같은데 쉽지 않다.
// Settings > Build, Execution, Deployment > Build Tools > Gradle > Build and Run > gradle 선택
springBoot {
    buildInfo()
}

tasks.named('build').get().finalizedBy('build-docker-image')
tasks.register('build-docker-image', Exec) {
    workingDir projectDir
    executable "/usr/local/bin/docker"
    args "build",
            "--build-arg", "APP_NAME=actuator",
            "--build-arg", "APP_VERSION=${version}",
            "-t", "jihogrammer/actuator:${version}",
            "-t", "jihogrammer/actuator:latest",
            "."
}
