spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

logging:
  level:
    dev.jihogrammer: TRACE
  pattern:
    console: "%magenta([%d{HH:MM:ss}]) %highlight([%5.5level]) %green([%25.25logger{25}]) %blue([%t]) %cyan([%X{transaction.id}]) - %msg%n"
