service:
  items:
    home:
      enabled: true
  core:
    memory:
#      enabled: true
      enabled: on

logging:
  level:
    dev.jihogrammer: TRACE
  pattern:
    console:
      "%magenta([%d{HH:MM:ss}])
      %highlight([%5.5level])
      %green([%25.25logger{25}])
      %cyan([%X{transaction.id}]) - %msg%n"
