info:
  app:
    name: actuator
    version: 0.0.1

management:
  # 왜 이렇게 이상하게 설정할까?
  # info 정보는 management 바로 하위에 구성한다.
  info:
    java.enabled: true
    os.enabled: true
    env.enabled: true
  # 기본적으로 활성화되지 않는 기능
  # curl -X POST localhost:8080/actuator/shutdown
  endpoint:
    shutdown.enabled: true
    health:
      # show-details: always
      show-components: always

  # actuator 기능을 사용하려면 활성화, 노출 모두 해야 가능하다.
  endpoints:
    web:
      exposure:
        include: "*"
